"""Emit seed SQL from the built lexicon CSVs.

Produces data/dist/seed.sql: portable INSERT statements that load into either
schema in sql/. Ids are carried over from the CSVs so the foreign keys line up.

Run: python export_sql.py
"""

import csv
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DIST = os.path.join(HERE, "data", "dist")
OUT = os.path.join(DIST, "seed.sql")


def quote(value):
    return "'" + str(value).replace("\\", "\\\\").replace("'", "''") + "'"


def rows(name):
    with open(os.path.join(DIST, name), encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def insert_block(table, columns, records, render):
    lines = [f"INSERT INTO {table} ({', '.join(columns)}) VALUES"]
    values = [f"  ({render(r)})" for r in records]
    lines.append(",\n".join(values) + ";")
    return "\n".join(lines)


def main():
    bad_words = rows("bad_words.csv")
    variations = rows("word_variations.csv")
    whitelist = rows("whitelist.csv")

    parts = [
        "-- Seed data for the Azerbaijani bad-word lexicon.",
        "-- Generated by export_sql.py -- edit data/roots.csv and rebuild instead.",
        "-- Load sql/schema_mysql.sql or sql/schema_postgres.sql first.",
        "",
        "DELETE FROM WordVariations;",
        "DELETE FROM BadWords;",
        "DELETE FROM Whitelist;",
        "",
        insert_block(
            "BadWords", ["Id", "Word", "NormalizedWord", "Category", "Severity"],
            bad_words,
            lambda r: f"{r['Id']}, {quote(r['Word'])}, {quote(r['NormalizedWord'])}, "
                      f"{quote(r['Category'])}, {r['Severity']}",
        ),
        "",
        insert_block(
            "WordVariations",
            ["Id", "BadWordId", "Variation", "NormalizedVariation", "Source"],
            variations,
            lambda r: f"{r['Id']}, {r['BadWordId']}, {quote(r['Variation'])}, "
                      f"{quote(r['NormalizedVariation'])}, {quote(r['Source'])}",
        ),
        "",
        insert_block(
            "Whitelist", ["Phrase", "NormalizedPhrase", "Scope", "Reason"], whitelist,
            lambda r: f"{quote(r['Phrase'])}, {quote(r['NormalizedPhrase'])}, "
                      f"{quote(r['Scope'])}, {quote(r['Reason'])}",
        ),
        "",
    ]

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))

    print(f"seed.sql written: {len(bad_words)} bad words, "
          f"{len(variations)} variations, {len(whitelist)} whitelist entries")
    print(f"-> {OUT}")


if __name__ == "__main__":
    main()
